version: "3.5"

services:
  db:
    image: postgres:13.9-alpine3.17
    volumes:
      - database-volume:/var/lib/postgresql/data
      - ./dump:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: marketplace
      POSTGRES_USER: marketplace_user
      POSTGRES_PASSWORD: marketplace_password
    ports:
      - "127.0.0.1:5432:5432"
    container_name: marketplace-database
volumes:
  database-volume: {}
networks:
  default:
    name: simple-marketplace
