openapi: 3.0.0
info:
    title: Item CRUD Operations API
    version: 1.0.0
servers:
    - url: https://api.example.com/v1
paths:
    /items:
        get:
            summary: Retrieve a list of all items
            responses:
                200:
                    description: A list of all items
                    content:
                        application/json:
                            schema:
                                type: array
                                items:
                                    $ref: "#/components/schemas/Item"
        post:
            summary: Create a new item
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Item"
            responses:
                201:
                    description: The newly created item
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Item"
    /items/{id}:
        get:
            summary: Retrieve a specific item by id
            parameters:
                - name: id
                  in: path
                  required: true
                  description: The id of the item to retrieve
                  schema:
                      type: integer
            responses:
                200:
                    description: The requested item
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Item"
        patch:
            summary: Update a specific item by id
            security:
                - bearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  description: The id of the item to update
                  schema:
                      type: integer
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/Item"
            responses:
                200:
                    description: The updated item
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Item"
        delete:
            summary: Delete a specific item by id
            security:
                - bearerAuth: []
            parameters:
                - name: id
                  in: path
                  required: true
                  description: The id of the item to delete
                  schema:
                      type: integer
            responses:
                204:
                    description: The item has been successfully deleted
components:
    schemas:
        Item:
            type: object
            properties:
                id:
                    type: integer
                    description: The id of the item
                owner:
                    type: integer
                    description: The id of the user who created the item
                name:
                    type: string
                    description: The name of the item
                description:
                    type: string
                    description: The description of the item
                tags:
                    type: array
                    items:
                        type: string
                    description: A list of tags associated with the item
                image:
                    type: string
                    description: An image of the item
                ratings:
                    type: array
                    items:
                        type: integer
                    description: A list of ratings given to the item
                price:
                    type: number
                    description: The price of the item
                    required:
                        - name
                        - price
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
            bearerFormat: JWT
