name: Continuous Integration

on:
  push:
    branches: [main, qa]
  pull_request:
    branches: [main, qa]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run lint check
        run: yarn eslint

      - name: Run prettier check
        run: yarn prettier:check

      - name: Run the tests
        run: yarn test
