name: Code Coverage

on: [pull_request]

jobs:
  base_branch_cov:
    runs-on: ubuntu-latest
    container: node:16.13.0

    services:
      postgres:
        image: postgres:15.1-alpine3.17
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
      - name: Use Node.js v16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: v16.13.0

      - name: Install dependencies
        run: yarn

      - name: Run test coverage
        run: yarn test
        env:
          POSTGRES_HOST: postgres
          DATABASE_URL: postgresql://prisma:prisma@postgres:5432/tests?schema=public

      - name: Upload code coverage for ref branch
        uses: actions/upload-artifact@v3
        with:
          name: ref-lcov.info
          path: ./coverage/lcov.info

  checks:
    runs-on: ubuntu-latest
    needs: base_branch_cov
    container: node:16.13.0

    services:
      postgres:
        image: postgres:15.1-alpine3.17
        env:
          POSTGRES_USER: prisma
          POSTGRES_PASSWORD: prisma
          POSTGRES_DB: tests
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js v16.13.0
        uses: actions/setup-node@v3
        with:
          node-version: v16.13.0

      - name: Download code coverage report from base branch
        uses: actions/download-artifact@v3
        with:
          name: ref-lcov.info

      - name: Install dependencies
        run: yarn

      - name: Run test coverage
        run: yarn test
        env:
          POSTGRES_HOST: postgres
          DATABASE_URL: postgresql://prisma:prisma@postgres:5432/tests?schema=public

      #  Compares two code coverage files and generates report as a comment
      - name: Generate Code Coverage report
        id: code-coverage
        uses: barecheck/code-coverage-action@v1
        with:
          barecheck-github-app-token: ${{ secrets.BARECHECK_GITHUB_APP_TOKEN }}
          lcov-file: "./coverage/lcov.info"
          base-lcov-file: "./lcov.info"
          minimum-ratio: 10 # Fails Github action once code coverage is below 90%
          send-summary-comment: true
          show-annotations: "warning" # Possible options warning|error
